enableGlobalCache: false

packageExtensions:
  local-pkg@*:
    dependencies:
      "@vitest/coverage-istanbul": "*"
      happy-dom: "*"
      vitest: "*"
  '@storybook/core-common@*':
     dependencies:
       '@storybook/react-vite': '*'
       'react': '*'
       'react-dom': '*'
       'vite': '*'
  '@storybook/react-dom-shim@*':
    dependencies:
      react-dom: '*'

yarnPath: .yarn/releases/yarn-remote.cjs
